### ISSUE TITLE
No readme on how to install and use the Python 3 version of the module

### ISSUE THREAD

**Issue by acerock6** [jacopofar/RDRPOSTagger-python-3#1]
Hi,

Thanks for the porting the Tagger to Python 3. But due to lack of any documentation or readme on how to use this particular version, I am not able to get any info and hence have got stuck.

**Comment by jacopofar** [comment]
Hello,
if I remember correctly there are no dependencies, and the usage is described in `FullUsage.html` file in the root of the project.

However I'll now add some examples also in the README.md

**Comment by jacopofar** [comment]
Done! Hope it helps :)

**Comment by acerock6** [comment]
Thanks @jacopofar . I actually got going with the usage from your Quora answer. But thanks for the quick revert :)
